=== msuliborski/monuments-database/piotr i lukasz/electronics-shop.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:pt="http://www.xmlTechnology.org/product-type"
           targetNamespace="http://www.xmlTechnology.org/electronics-shop-namespace"
           elementFormDefault="qualified">

    <xs:import schemaLocation="product-type.xsd" namespace="http://www.xmlTechnology.org/product-type"/>

    <!--  definition of simple elements -->
    <xs:element name="electronics-shop" type="electronics-shop_type">

        <!-- definition of key/keyref -->
        <xs:keyref name="manufacturer-id_keyRef" refer="manufacturer-id_key">
            <xs:selector xpath="manufacturer/*"/>
            <xs:field xpath="@manufacturer-id"/>
        </xs:keyref>
        <xs:key name="manufacturer-id_key">
            <xs:selector xpath="product/*"/>
            <xs:field xpath="manufacturer-id"/>
        </xs:key>

    </xs:element>

    <xs:element name="document-information" type="document-information_type"/>
    <xs:element name="data" type="data_type"/>

    <xs:element name="author" type="author_type" />
    <xs:element name="description" type="xs:string"/>

    <xs:element name="first-name" type="xs:string"/>
    <xs:element name="last-name" type="xs:string" />
    <xs:element name="student-id" type="xs:integer"/>

    <xs:element name="categories" type="categories_type"/>
    <xs:element name="products-list" type="products-list_type"/>

    <xs:element name="product-types" type="product-types_type"/>

    <xs:element name="manufacturer" type="manufacturer_type"/>

    <xs:element name="manufacturer-name" type="xs:string"/>
    <xs:element name="headquarters" type="headquarters_type"/>
    <xs:element name="factory" type="xs:string"/>

    <xs:element name="location" type="xs:string"/>
    <xs:element name="country" type="xs:string"/>

    <xs:element name="product-type" type="pt:product-type_type"/>

    <xs:element name="product" type="product_type"/>
    <xs:element name="name" type="xs:string"/>
    <xs:element name="price" type="price_type"/>
    <xs:element name="release-date" type="release-date_type"/>
    <xs:element name="warranty" type="warranty_type"/>
    <xs:element name="specification" type="specification_type"/>
    <xs:element name="user-rating" type="user-rating_type"/>
    <xs:element name="in-stock" type="xs:integer"/>
    <xs:element name="free-delivery" type="free-delivery_type"/>
    <xs:element name="additional-information" type="xs:string"/>

    <xs:element name="day" type="xs:integer"/>
    <xs:element name="month" type="xs:integer"/>
    <xs:element name="year" type="xs:integer"/>
    
    <xs:element name="weight" type="weight_type"/>
    <xs:element name="display-size" type="display-size_type"/>
    <xs:element name="color" type="xs:string"/>
    <xs:element name="switch" type="xs:string"/>
    <xs:element name="sensor" type="xs:string"/>


    <!-- definition of attributes -->
    <xs:attributeGroup name="product-attributes">
        <xs:attribute name="product-id" type="xs:ID" use="required"/>
        <xs:attribute name="category-id" type="xs:IDREF" use="required"/>
        <xs:attribute name="manufacturer-id" type="xs:string" use="required"/>
    </xs:attributeGroup>

    <!-- definition of group elements -->
    <xs:group name="product_elements">
        <xs:sequence>
            <xs:element ref="name"/>
            <xs:element ref="price"/>
            <xs:element ref="release-date"/>
            <xs:element ref="warranty"/>
            <xs:element ref="specification"/>
            <xs:element ref="user-rating"/>
            <xs:element ref="in-stock"/>
            <xs:element ref="free-delivery"/>
            <xs:element ref="additional-information"/>
        </xs:sequence>
    </xs:group>

    <!-- definition of simple types -->
    <xs:simpleType name="user-rating_type">
        <xs:restriction base="xs:double">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="5"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="currency_type">
        <xs:restriction>
            <xs:enumeration value="pln"/>
            <xs:enumeration value="usd"/>
            <xs:enumeration value="czk"/>
            <xs:enumeration value="gbp"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- definition of complex types -->
    <xs:complexType name="electronics-shop_type">
        <xs:sequence>
            <xs:element ref="document-information"/>
            <xs:element ref="data"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="document-information_type">
        <xs:sequence>
            <xs:element ref="author" minOccurs="2" maxOccurs="2"/>
            <xs:element ref="description"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="author_type" >
        <xs:sequence>
            <xs:element ref="first-name"/>
            <xs:element ref="last-name"/>
            <xs:element ref="student-id"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="data_type">
        <xs:sequence>
            <xs:element ref="categories"/>
            <xs:element ref="products-list"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="categories_type">
        <xs:sequence>
            <xs:element name="manufacturers">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element ref="manufacturer" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element ref="product-types"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="manufacturer_type">
        <xs:sequence>
            <xs:element ref="manufacturer-name"/>
            <xs:element ref="headquarters"/>
            <xs:element ref="factory"/>
        </xs:sequence>
        <xs:attribute name="manufacturer-id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="headquarters_type">
        <xs:sequence>
            <xs:element ref="location"/>
            <xs:element ref="country"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="product-types_type">
        <xs:sequence maxOccurs="8">
            <xs:element ref="product-type"/>
        </xs:sequence>
        <xs:attribute name="class"/>
        <xs:attribute name="title"/>
    </xs:complexType>

    <xs:complexType name="product_type">
        <xs:group ref="product_elements"/>
        <xs:attributeGroup ref="product-attributes"/>
    </xs:complexType>
    
    <xs:complexType name="products-list_type">
        <xs:sequence maxOccurs="unbounded">
            <xs:element ref="product"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="price_type">
        <xs:simpleContent>
        <xs:extension base="xs:double">
            <xs:attribute name="currency" type="currency_type"/>
            <xs:attribute name="on-sale" type="xs:string"/>
        </xs:extension>
    </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="release-date_type">
        <xs:sequence>
            <xs:element ref="day"/>
            <xs:element ref="month"/>
            <xs:element ref="year"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="warranty_type">
        <xs:simpleContent>
            <xs:extension base="xs:integer">
                <xs:attribute name="time-unit" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="specification_type">
        <xs:sequence>
            <xs:element ref="weight"/>
            <xs:element ref="display-size" minOccurs="0"/>
            <xs:element ref="color"/>
            <xs:choice>
                <xs:element ref="switch" minOccurs="0"/>
                <xs:element ref="sensor" minOccurs="0"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="free-delivery_type">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="available">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="available|non-available"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="weight_type">
        <xs:simpleContent>
            <xs:extension base="xs:double">
                <xs:attribute name="weight-unit">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="g"/>
                            <xs:enumeration value="kg"/>
                            <xs:enumeration value="pounds"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="display-size_type">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="display_size-unit"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

</xs:schema>

=== msuliborski/monuments-database/piotr i lukasz/electronics-shop.xml
<?xml version="1.0" encoding="utf-8" ?>
<es:electronics-shop
        xmlns:es="http://www.xmlTechnology.org/electronics-shop-namespace"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.xmlTechnology.org/electronics-shop-namespace electronics-shop.xsd">
    <document-information>
        <author>
            <first-name>≈Åukasz</first-name>
            <last-name>Starosta</last-name>
            <student-id>217862</student-id>
        </author>
        <author>
            <first-name>Piotr</first-name>
            <last-name>Karczewski</last-name>
            <student-id>217846</student-id>
        </author>
        <description>
        This XML document contains an example of an online electronics shop. To the left, there are different categories like manufacturers of the products (e.g. Samsung or Apple) and product types (e.g. mouse or keyboard). To the right, there is a list of all the products in the shop with additional information about them.
        </description>
    </document-information>
    <data>
        <categories>
            <manufacturers>
                <manufacturer manufacturer-id="samsung">
                    <manufacturer-name>Samsung</manufacturer-name>
                    <headquarters>
                        <location>Seul</location>
                        <country>South Korea</country>
                    </headquarters>
                    <factory>Taiwan</factory>
                </manufacturer>
                <manufacturer manufacturer-id="apple">
                    <manufacturer-name>Apple</manufacturer-name>
                    <headquarters>
                        <location>Apple Park</location>
                        <country>United States</country>
                    </headquarters>
                    <factory>China</factory>
                </manufacturer>
                <manufacturer manufacturer-id="oneplus">
                    <manufacturer-name>OnePlus</manufacturer-name>
                    <headquarters>
                        <location>Shenzen</location>
                        <country>China</country>
                    </headquarters>
                    <factory>Taiwan</factory>
                </manufacturer>
                <manufacturer manufacturer-id="razer">
                    <manufacturer-name>Razer</manufacturer-name>
                    <headquarters>
                        <location>San Francisco</location>
                        <country>United States</country>
                    </headquarters>
                    <factory>China</factory>
                </manufacturer>
                <manufacturer manufacturer-id="acer">
                    <manufacturer-name>Acer</manufacturer-name>
                    <headquarters>
                        <location>New Taipei</location>
                        <country>China</country>
                    </headquarters>
                    <factory>China</factory>
                </manufacturer>
                <manufacturer manufacturer-id="asus">
                    <manufacturer-name>Asus</manufacturer-name>
                    <headquarters>
                        <location>Beitou</location>
                        <country>China</country>
                    </headquarters>
                    <factory>Taiwan</factory>
                </manufacturer>
                <manufacturer manufacturer-id="dell">
                    <manufacturer-name>Dell</manufacturer-name>
                    <headquarters>
                        <location>Round Rock</location>
                        <country>United States</country>
                    </headquarters>
                    <factory>China</factory>
                </manufacturer>
            </manufacturers>
            <product-types>
                <product-type category-id="notebook">Notebook</product-type>
                <product-type category-id="smartphone">Smartphone</product-type>
                <product-type category-id="tv">TV</product-type>
                <product-type category-id="monitor">Monitor</product-type>
                <product-type category-id="accessory">Accesory</product-type>
                <product-type category-id="keyboard">Keyboard</product-type>
                <product-type category-id="mouse">Mouse</product-type>
                <product-type category-id="hoverboard">Hoverboard</product-type>
            </product-types>
        </categories>
        <products-list>
            <product product-id="i50" category-id="notebook" manufacturer-id="acer">
                <name>Acer Swift 3</name>
                <price currency="pln" on-sale="no">2000</price>
                <release-date>
                    <day>23</day>
                    <month>1</month>
                    <year>2017</year>
                </release-date>
                <warranty time-unit="years">2</warranty>
                <specification>
                    <weight weight-unit="g">1200</weight>
                    <display-size display_size-unit="inch">13.3</display-size>
                    <color>Silver</color>
                </specification>
                <user-rating>4</user-rating>
                <in-stock>23</in-stock>
                <free-delivery available="available"/>
                <additional-information/>
            </product>
            <product product-id="i51" category-id="notebook" manufacturer-id="apple">
                <name>Apple MacBook Pro</name>
                <price currency="pln" on-sale="yes">3699</price>
                <release-date>
                    <day>3</day>
                    <month>4</month>
                    <year>2018</year>
                </release-date>
                <warranty time-unit="years">2</warranty>
                <specification>
                    <weight weight-unit="g">1050</weight>
                    <display-size display_size-unit="inch">15</display-size>
                    <color>Space Gray</color>
                </specification>
                <user-rating>4.5</user-rating>
                <in-stock>1305</in-stock>
                <free-delivery available="available"/>
                <additional-information>Version with US keyboard layout.</additional-information>
            </product>
            <product product-id="i52" category-id="smartphone" manufacturer-id="samsung">
                <name>Samsung Galaxy S9 Plus</name>
                <price currency="pln" on-sale="no">3299</price>
                <release-date>
                    <day>12</day>
                    <month>11</month>
                    <year>2018</year>
                </release-date>
                <warranty time-unit="years">2</warranty>
                <specification>
                    <weight weight-unit="g">650</weight>
                    <display-size display_size-unit="inch">6.7</display-size>
                    <color>Midnight Black</color>
                </specification>
                <user-rating>4.7</user-rating>
                <in-stock>784</in-stock>
                <free-delivery available="available"/>
                <additional-information>Free wireless charger with every order.</additional-information>
            </product>
            <product product-id="i53" category-id="smartphone" manufacturer-id="apple">
                <name>Apple IPhone X</name>
                <price currency="pln" on-sale="no">3893</price>
                <release-date>
                    <day>14</day>
                    <month>6</month>
                    <year>2018</year>
                </release-date>
                <warranty time-unit="years">3</warranty>
                <specification>
                    <weight weight-unit="g">740</weight>
                    <display-size display_size-unit="inch">5.8</display-size>
                    <color>Rose Gold</color>
                </specification>
                <user-rating>4.4</user-rating>
                <in-stock>2154</in-stock>
                <free-delivery available="available"/>
                <additional-information/>
            </product>
            <product product-id="i54" category-id="notebook" manufacturer-id="dell">
                <name>Dell Inspiron 5379</name>
                <price currency="pln" on-sale="yes">3259</price>
                <release-date>
                    <day>2</day>
                    <month>3</month>
                    <year>2017</year>
                </release-date>
                <warranty time-unit="years">2</warranty>
                <specification>
                    <weight weight-unit="g">1230</weight>
                    <display-size display_size-unit="inch">13.3</display-size>
                    <color>Matte Grey</color>
                </specification>
                <user-rating>4.1</user-rating>
                <in-stock>521</in-stock>
                <free-delivery available="available"/>
                <additional-information>Version with touchscreen.</additional-information>
            </product>
            <product product-id="i55" category-id="keyboard" manufacturer-id="razer">
                <name>Razer Blackwidow Chroma</name>
                <price currency="pln" on-sale="no">549</price>
                <release-date>
                    <day>12</day>
                    <month>10</month>
                    <year>2016</year>
                </release-date>
                <warranty time-unit="years">2</warranty>
                <specification>
                    <weight weight-unit="g">970</weight>
                    <color>Black</color>
                    <switch>Cherry MX Silent</switch>
                </specification>
                <user-rating>4.9</user-rating>
