=== msuliborski/monuments-database/task-1/monuments-database.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT monuments-database (title, authors, monuments, cities, types)>

    <!ELEMENT title (#PCDATA)>

    <!ELEMENT authors (author+)>
        <!ELEMENT author (first-name, last-name, student-id)>
            <!ELEMENT first-name (#PCDATA)>
            <!ELEMENT last-name (#PCDATA)>
            <!ELEMENT student-id (#PCDATA)>

    <!ELEMENT monuments ANY>
        <!ELEMENT monument (monument-name, monument-author, completion-date, costs, dimensions, visiting, history)>
            <!ATTLIST monument monument-id ID #REQUIRED>
            <!ATTLIST monument type-id IDREF #REQUIRED>
            <!ATTLIST monument city-id IDREF #REQUIRED>
            <!ELEMENT monument-name (#PCDATA)>
            <!ELEMENT monument-author (#PCDATA)>
            <!ELEMENT completion-date (completion-day, completion-month, completion-year)>
                <!ELEMENT completion-day (#PCDATA)>
                <!ELEMENT completion-month (#PCDATA)>
                <!ELEMENT completion-year (#PCDATA)>
            <!ELEMENT costs (#PCDATA)>
                <!ATTLIST costs currency CDATA #IMPLIED>
            <!ELEMENT dimensions (width, height, length)>
                <!ELEMENT width (#PCDATA)>
                    <!ATTLIST width unit CDATA #REQUIRED>
                <!ELEMENT height (#PCDATA)>
                    <!ATTLIST height unit CDATA #REQUIRED>
                <!ELEMENT length (#PCDATA)>
                    <!ATTLIST length unit CDATA #REQUIRED>
            <!ELEMENT visiting (#PCDATA)>
            <!ELEMENT history (#PCDATA)>

    <!ELEMENT cities (city*)>
        <!ELEMENT city (city-name, country, governing-mayor, area, elevation, population, establishment-date)>
            <!ATTLIST city city-id ID #REQUIRED>
            <!ELEMENT city-name (#PCDATA)>
            <!ELEMENT country (#PCDATA)>
            <!ELEMENT governing-mayor (#PCDATA)>
            <!ELEMENT area (#PCDATA)>
                <!ATTLIST area unit CDATA #FIXED "km2">
            <!ELEMENT elevation (lowest-level, highest-level)>
                <!ELEMENT lowest-level (#PCDATA)>
                    <!ATTLIST lowest-level unit CDATA #REQUIRED>
                <!ELEMENT highest-level (#PCDATA)>
                    <!ATTLIST highest-level unit CDATA #REQUIRED>
            <!ELEMENT population (#PCDATA)>
            <!ELEMENT establishment-date (establishment-day, establishment-month, establishment-year)>
                <!ELEMENT establishment-day (#PCDATA)>
                <!ELEMENT establishment-month (#PCDATA)>
                <!ELEMENT establishment-year (#PCDATA)>

    <!ELEMENT types (type+)>
        <!ELEMENT type (#PCDATA)>
            <!ATTLIST type type-id ID #REQUIRED>
            <!ATTLIST type class NMTOKEN #IMPLIED>

=== msuliborski/monuments-database/monuments-database.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="monuments-database.css" type="text/css"?>
<!--<!DOCTYPE monuments-database SYSTEM "monuments-database.dtd">-->

<main:monuments-database
        xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
        xsd:schemaLocation="https://www.monuments-database.com monuments-database.xsd"
        xmlns:main="https://www.monuments-database.com"
        xmlns:el="https://www.monuments-database.com/elements">

    <main:title>Monuments Database</main:title>

    <main:authors>
        <main:author>
            <main:first-name>Michał</main:first-name>
            <main:last-name>Suliborski</main:last-name>
            <main:student-id>217863</main:student-id>
        </main:author>

        <main:author>
            <main:first-name>Mariusz</main:first-name>
            <main:last-name>Pisarski</main:last-name>
            <main:student-id>217857</main:student-id>
        </main:author>
    </main:authors>

    <main:monuments>
        <el:monument monument-id="eiffel-tower" city-id="paris" type-id="observation-tower">
            <el:monument-name>Eiffel Tower</el:monument-name>
            <el:monument-author>Stephen Sauvestre</el:monument-author>
            <el:completion-date>
                <el:completion-day>15</el:completion-day>
                <el:completion-month>03</el:completion-month>
                <el:completion-year>1889</el:completion-year>
            </el:completion-date>
            <el:costs currency="CHF">1500000000</el:costs>
            <el:dimensions>
                <el:width unit="m">124.9</el:width>
                <el:height unit="m">324</el:height>
                <el:length unit="m">124.9</el:length>
            </el:dimensions>
            <el:visiting>available</el:visiting>
            <el:history>Eiffel Tower is a wrought iron lattice tower on the Champ de Mars in Paris, France.
                It is named after the engineer Gustave Eiffel, whose company designed and built the tower.
            </el:history>
        </el:monument>

        <el:monument monument-id="colosseum" city-id="rome" type-id="building">
            <el:monument-name>Colosseum</el:monument-name>
            <el:monument-author>Vespasian</el:monument-author>
            <el:completion-date>
                <el:completion-day>01</el:completion-day>
                <el:completion-month>01</el:completion-month>
                <el:completion-year>80</el:completion-year>
            </el:completion-date>
            <el:costs currency="ITL">40000000000</el:costs>
            <el:dimensions>
                <el:width unit="m">156</el:width>
                <el:height unit="m">48.5</el:height>
                <el:length unit="m">188</el:length>
            </el:dimensions>
            <el:visiting>available</el:visiting>
            <el:history>
                Colosseum is an oval amphitheatre in the centre of the city of Rome, Italy.
                Built of travertine, tuff, and brick-faced concrete, it is the largest amphitheatre ever built.
                The Colosseum is situated just east of the Roman Forum.
                Construction began under the emperor Vespasian in AD 72, and was completed in AD 80 under his successor
                and heir Titus.
                Further modifications were made during the reign of Domitian.
                These three emperors are known as the Flavian dynasty, and the amphitheatre was named in Latin for its
                association with their family name (Flavius).
            </el:history>
        </el:monument>

        <el:monument monument-id="berlin-wall" city-id="berlin" type-id="wall">
            <el:monument-name>Berlin Wall</el:monument-name>
            <el:monument-author>German Democratic Republic</el:monument-author>
            <el:completion-date>
                <el:completion-day>13</el:completion-day>
                <el:completion-month>8</el:completion-month>
                <el:completion-year>1961</el:completion-year>
            </el:completion-date>
            <el:costs currency="DM">22500000000</el:costs>
            <el:dimensions>
                <el:width unit="m">156</el:width>
                <el:height unit="m">4.2</el:height>
                <el:length unit="m">111.9</el:length>
            </el:dimensions>
            <el:visiting>available</el:visiting>
            <el:history>
                Berlin Wall was a guarded concrete barrier that physically and ideologically divided Berlin from 1961 to
                1989.
                Constructed by the German Democratic Republic, starting on 13 August 1961,
                the Wall cut off West Berlin from virtually all of surrounding East Germany and East Berlin until
                government officials opened it in November 1989.
                Its demolition officially began on 13 June 1990 and finished in 1992.
                The barrier included guard towers placed along large concrete walls, accompanied by a wide area that
                contained anti-vehicle trenches, "fakir beds" and other defenses.
                The Eastern Bloc portrayed the Wall as protecting its population from fascist elements conspiring to
                prevent the "will of the people" in building a socialist state in East Germany.
            </el:history>
        </el:monument>

        <el:monument monument-id="leaning-tower-of-pisa" city-id="pisa" type-id="observation-tower">
            <el:monument-name>Leaning Tower of Pisa</el:monument-name>
            <el:monument-author>Bonanno Pisano</el:monument-author>
            <el:completion-date>
                <el:completion-day>04</el:completion-day>
                <el:completion-month>08</el:completion-month>
                <el:completion-year>1173</el:completion-year>
            </el:completion-date>
            <el:costs currency="USD">2900000</el:costs>
            <el:dimensions>
                <el:width unit="m">11.5</el:width>
                <el:height unit="m">55.86</el:height>
                <el:length unit="m">11.5</el:length>
            </el:dimensions>
            <el:visiting>available</el:visiting> <!--available/non-available -->
            <el:history>
                Leaning Tower of Pisa is the campanile, or freestanding bell tower, of the cathedral of the Italian city
                of Pisa, known worldwide for its unintended tilt.
                The tower is situated behind the Pisa Cathedral and is the third oldest structure in the city's
                Cathedral Square (Piazza del Duomo),
                after the cathedral and the Pisa Baptistry.
            </el:history>
        </el:monument>

        <el:monument monument-id="notre-dame-de-paris" city-id="paris" type-id="building">
            <el:monument-name>Notre-Dame de Paris</el:monument-name>
            <el:monument-author>Unknown</el:monument-author>
            <el:completion-date>
                <el:completion-day>35</el:completion-day>
                <el:completion-month>04</el:completion-month>
                <el:completion-year>1345</el:completion-year>
            </el:completion-date>
            <el:costs currency="CHF">24500000000</el:costs>
            <el:dimensions>
                <el:width unit="m">48</el:width>
                <el:height unit="m">90</el:height>
                <el:length unit="m">128</el:length>
            </el:dimensions>
            <el:visiting>available</el:visiting>
            <el:history>
                Notre-Dame de Paris is a medieval Catholic cathedral on the Île de la Cité in the fourth arrondissement
                of Paris, France.
                The cathedral is widely considered to be one of the finest examples of French Gothic architecture.
                The innovative use of the rib vault and flying buttress, the enormous and colorful rose windows,
                and the naturalism and abundance of its sculptural decoration all set it apart from earlier Romanesque
                architecture.
            </el:history>
        </el:monument>

        <el:monument monument-id="big-ben" city-id="london" type-id="building">
            <el:monument-name>Big Ben</el:monument-name>
            <el:monument-author>Augustus Pugin</el:monument-author>
            <el:completion-date>
                <el:completion-day>31</el:completion-day>
                <el:completion-month>05</el:completion-month>
                <el:completion-year>1859</el:completion-year>
            </el:completion-date>
            <el:costs currency="GBP">61000000</el:costs>
            <el:dimensions>
                <el:width unit="m">23</el:width>
                <el:height unit="m">96</el:height>
                <el:length unit="m">23</el:length>
            </el:dimensions>
            <el:visiting>available</el:visiting>
            <el:history>
                Big Ben is the nickname for the Great Bell of the clock at the north end of the Palace of Westminster in
                London and is usually extended to refer to both
                the clock and the clock tower. The official name of the tower in which Big Ben is located was originally
                the Clock Tower,
                but it was renamed Elizabeth Tower in 2012 to mark the Diamond Jubilee of Elizabeth II.
            </el:history>
        </el:monument>

        <el:monument monument-id="cattedrale-di-santa-maria-del-fiore" city-id="florence" type-id="church-cathedral">
            <el:monument-name>Cattedrale di Santa Maria del Fiore</el:monument-name>
            <el:monument-author>Arnolfo di Cambio</el:monument-author>
            <el:completion-date>
                <el:completion-day>09</el:completion-day>
                <el:completion-month>09</el:completion-month>
                <el:completion-year>1296</el:completion-year>
            </el:completion-date>
            <el:costs currency="ITL">48000000</el:costs>
            <el:dimensions>
